// GENERATED by scripts/gen-forms.ts — do not edit by hand.
// Source: PokeAPI (https://pokeapi.co). Mega, Gigantamax and fusion forms.
// Sprites themselves are never bundled; they are fetched at runtime.

import type { MoveType } from './moves.ts';

export type FormKind = 'mega' | 'gmax' | 'fusion';

/**
 * One alternate form — the second axis a companion can move along.
 *
 * The first axis is `stageIndex` walking `pathIds`, which never leaves the
 * 1025 base species. A form sits beside that: it replaces what is DRAWN and
 * NAMED without touching which species the companion is for the dex, its
 * rarity, its learnset or its evolution line.
 */
export type Form = {
  /**
   * PokeAPI pokemon id, which is also the sprite id.
   *
   * That equality is why this whole feature needs no change to
   * server/sprites.ts: `ensureSprite` resolves any number, and its
   * `id <= BW_MAX_ID ? 0 : 1` already starts these above the Gen-5 tier.
   */
  id: number;
  /** The base species. Dex, rarity, learnset and the tray all keep using this. */
  base: number;
  kind: FormKind;
  ko: string;
  en: string;
  /**
   * Display ids this form can be reached from. Usually just `[base]`.
   *
   * Ultra Necrozma is the reason this is a list: it is an Ultra Burst on an
   * ALREADY-FUSED Necrozma, so it is reachable only from two other forms.
   */
  from: number[];
  types: MoveType[];
  /**
   * Form base-stat total over the base species'.
   *
   * Measured, not invented: every mega is a flat +100 (about 1.19), and every
   * gigantamax is exactly 1 — Gigantamax changes no stat in the games, it
   * doubles HP, which this app expresses as halved incoming damage instead.
   */
  power: number;
  heightM: number;
  weightKg: number;
  /** Mega only: the stone that opens it. `sprite` is null where PokeAPI has no icon. */
  stone?: { ko: string; sprite: string | null };
  /** Fusion only: the species that must already be in the dex. */
  partner?: number;
};

export const FORMS: Form[] = [
  {
    "id": 10022,
    "base": 646,
    "types": [
      "dragon",
      "ice"
    ],
    "power": 1.061,
    "heightM": 3.3,
    "weightKg": 325,
    "kind": "fusion",
    "ko": "블랙큐레무",
    "en": "Black Kyurem",
    "from": [
      646
    ],
    "partner": 644
  },
  {
    "id": 10023,
    "base": 646,
    "types": [
      "dragon",
      "ice"
    ],
    "power": 1.061,
    "heightM": 3.6,
    "weightKg": 325,
    "kind": "fusion",
    "ko": "화이트큐레무",
    "en": "White Kyurem",
    "from": [
      646
    ],
    "partner": 643
  },
  {
    "id": 10033,
    "base": 3,
    "types": [
      "grass",
      "poison"
    ],
    "power": 1.19,
    "heightM": 2.4,
    "weightKg": 155.5,
    "kind": "mega",
    "ko": "메가이상해꽃",
    "en": "Mega Venusaur",
    "from": [
      3
    ],
    "stone": {
      "ko": "이상해꽃나이트",
      "sprite": "venusaurite"
    }
  },
  {
    "id": 10034,
    "base": 6,
    "types": [
      "fire",
      "dragon"
    ],
    "power": 1.187,
    "heightM": 1.7,
    "weightKg": 110.5,
    "kind": "mega",
    "ko": "메가리자몽X",
    "en": "Mega Charizard X",
    "from": [
      6
    ],
    "stone": {
      "ko": "리자몽나이트X",
      "sprite": "charizardite-x"
    }
  },
  {
    "id": 10035,
    "base": 6,
    "types": [
      "fire",
      "flying"
    ],
    "power": 1.187,
    "heightM": 1.7,
    "weightKg": 100.5,
    "kind": "mega",
    "ko": "메가리자몽Y",
    "en": "Mega Charizard Y",
    "from": [
      6
    ],
    "stone": {
      "ko": "리자몽나이트Y",
      "sprite": "charizardite-y"
    }
  },
  {
    "id": 10036,
    "base": 9,
    "types": [
      "water"
    ],
    "power": 1.189,
    "heightM": 1.6,
    "weightKg": 101.1,
    "kind": "mega",
    "ko": "메가거북왕",
    "en": "Mega Blastoise",
    "from": [
      9
    ],
    "stone": {
      "ko": "거북왕나이트",
      "sprite": "blastoisinite"
    }
  },
  {
    "id": 10037,
    "base": 65,
    "types": [
      "psychic"
    ],
    "power": 1.2,
    "heightM": 1.2,
    "weightKg": 48,
    "kind": "mega",
    "ko": "메가후딘",
    "en": "Mega Alakazam",
    "from": [
      65
    ],
    "stone": {
      "ko": "후딘나이트",
      "sprite": null
    }
  },
  {
    "id": 10038,
    "base": 94,
    "types": [
      "ghost",
      "poison"
    ],
    "power": 1.2,
    "heightM": 1.4,
    "weightKg": 40.5,
    "kind": "mega",
    "ko": "메가팬텀",
    "en": "Mega Gengar",
    "from": [
      94
    ],
    "stone": {
      "ko": "팬텀나이트",
      "sprite": "gengarite"
    }
  },
  {
    "id": 10039,
    "base": 115,
    "types": [
      "normal"
    ],
    "power": 1.204,
    "heightM": 2.2,
    "weightKg": 100,
    "kind": "mega",
    "ko": "메가캥카",
    "en": "Mega Kangaskhan",
    "from": [
      115
    ],
    "stone": {
      "ko": "캥카나이트",
      "sprite": "kangaskhanite"
    }
  },
  {
    "id": 10040,
    "base": 127,
    "types": [
      "bug",
      "flying"
    ],
    "power": 1.2,
    "heightM": 1.7,
    "weightKg": 59,
    "kind": "mega",
    "ko": "메가쁘사이저",
    "en": "Mega Pinsir",
    "from": [
      127
    ],
    "stone": {
      "ko": "쁘사이저나이트",
      "sprite": "pinsirite"
    }
  },
  {
    "id": 10041,
    "base": 130,
    "types": [
      "water",
      "dark"
    ],
    "power": 1.185,
    "heightM": 6.5,
    "weightKg": 305,
    "kind": "mega",
    "ko": "메가갸라도스",
    "en": "Mega Gyarados",
    "from": [
      130
    ],
    "stone": {
      "ko": "갸라도스나이트",
      "sprite": "gyaradosite"
    }
  },
  {
    "id": 10042,
    "base": 142,
    "types": [
      "rock",
      "flying"
    ],
    "power": 1.194,
    "heightM": 2.1,
    "weightKg": 79,
    "kind": "mega",
    "ko": "메가프테라",
    "en": "Mega Aerodactyl",
    "from": [
      142
    ],
    "stone": {
      "ko": "프테라나이트",
      "sprite": "aerodactylite"
    }
  },
  {
    "id": 10043,
    "base": 150,
    "types": [
      "psychic",
      "fighting"
    ],
    "power": 1.147,
    "heightM": 2.3,
    "weightKg": 127,
    "kind": "mega",
    "ko": "메가뮤츠X",
    "en": "Mega Mewtwo X",
    "from": [
      150
    ],
    "stone": {
      "ko": "뮤츠나이트X",
      "sprite": "mewtwonite-x"
    }
  },
  {
    "id": 10044,
    "base": 150,
    "types": [
      "psychic"
    ],
    "power": 1.147,
    "heightM": 1.5,
    "weightKg": 33,
    "kind": "mega",
    "ko": "메가뮤츠Y",
    "en": "Mega Mewtwo Y",
    "from": [
      150
    ],
    "stone": {
      "ko": "뮤츠나이트Y",
      "sprite": "mewtwonite-y"
    }
  },
  {
    "id": 10045,
    "base": 181,
    "types": [
      "electric",
      "dragon"
    ],
    "power": 1.196,
    "heightM": 1.4,
    "weightKg": 61.5,
    "kind": "mega",
    "ko": "메가전룡",
    "en": "Mega Ampharos",
    "from": [
      181
    ],
    "stone": {
      "ko": "전룡나이트",
      "sprite": "ampharosite"
    }
  },
  {
    "id": 10046,
    "base": 212,
    "types": [
      "bug",
      "steel"
    ],
    "power": 1.2,
    "heightM": 2,
    "weightKg": 125,
    "kind": "mega",
    "ko": "메가핫삼",
    "en": "Mega Scizor",
    "from": [
      212
    ],
    "stone": {
      "ko": "핫삼나이트",
      "sprite": "scizorite"
    }
  },
  {
    "id": 10047,
    "base": 214,
    "types": [
      "bug",
      "fighting"
    ],
    "power": 1.2,
    "heightM": 1.7,
    "weightKg": 62.5,
    "kind": "mega",
    "ko": "메가헤라크로스",
    "en": "Mega Heracross",
    "from": [
      214
    ],
    "stone": {
      "ko": "헤라크로스나이트",
      "sprite": "heracronite"
    }
  },
  {
    "id": 10048,
    "base": 229,
    "types": [
      "dark",
      "fire"
    ],
    "power": 1.2,
    "heightM": 1.9,
    "weightKg": 49.5,
    "kind": "mega",
    "ko": "메가헬가",
    "en": "Mega Houndoom",
    "from": [
      229
    ],
    "stone": {
      "ko": "헬가나이트",
      "sprite": "houndoominite"
    }
  },
  {
    "id": 10049,
    "base": 248,
    "types": [
      "rock",
      "dark"
    ],
    "power": 1.167,
    "heightM": 2.5,
    "weightKg": 255,
    "kind": "mega",
    "ko": "메가마기라스",
    "en": "Mega Tyranitar",
    "from": [
      248
    ],
    "stone": {
      "ko": "마기라스나이트",
      "sprite": "tyranitarite"
    }
  },
  {
    "id": 10050,
    "base": 257,
    "types": [
      "fire",
      "fighting"
    ],
    "power": 1.189,
    "heightM": 1.9,
    "weightKg": 52,
    "kind": "mega",
    "ko": "메가번치코",
    "en": "Mega Blaziken",
    "from": [
      257
    ],
    "stone": {
      "ko": "번치코나이트",
      "sprite": "blazikenite"
    }
  },
  {
    "id": 10051,
    "base": 282,
    "types": [
      "psychic",
      "fairy"
    ],
    "power": 1.193,
    "heightM": 1.6,
    "weightKg": 48.4,
    "kind": "mega",
    "ko": "메가가디안",
    "en": "Mega Gardevoir",
    "from": [
      282
    ],
    "stone": {
      "ko": "가디안나이트",
      "sprite": "gardevoirite"
    }
  },
  {
    "id": 10052,
    "base": 303,
    "types": [
      "steel",
      "fairy"
    ],
    "power": 1.263,
    "heightM": 1,
    "weightKg": 23.5,
    "kind": "mega",
    "ko": "메가입치트",
    "en": "Mega Mawile",
    "from": [
      303
    ],
    "stone": {
      "ko": "입치트나이트",
      "sprite": "mawilite"
    }
  },
  {
    "id": 10053,
    "base": 306,
    "types": [
      "steel"
    ],
    "power": 1.189,
    "heightM": 2.2,
    "weightKg": 395,
    "kind": "mega",
    "ko": "메가보스로라",
    "en": "Mega Aggron",
    "from": [
      306
    ],
    "stone": {
      "ko": "보스로라나이트",
      "sprite": "aggronite"
    }
  },
  {
    "id": 10054,
    "base": 308,
    "types": [
      "fighting",
      "psychic"
    ],
    "power": 1.244,
    "heightM": 1.3,
    "weightKg": 31.5,
    "kind": "mega",
    "ko": "메가요가램",
    "en": "Mega Medicham",
    "from": [
      308
    ],
    "stone": {
      "ko": "요가램나이트",
      "sprite": "medichamite"
    }
  },
  {
    "id": 10055,
    "base": 310,
    "types": [
      "electric"
    ],
    "power": 1.211,
    "heightM": 1.8,
    "weightKg": 44,
    "kind": "mega",
    "ko": "메가썬더볼트",
    "en": "Mega Manectric",
    "from": [
      310
    ],
    "stone": {
      "ko": "썬더볼트나이트",
      "sprite": "manectite"
    }
  },
  {
    "id": 10056,
    "base": 354,
    "types": [
      "ghost"
    ],
    "power": 1.22,
    "heightM": 1.2,
    "weightKg": 13,
    "kind": "mega",
    "ko": "메가다크펫",
    "en": "Mega Banette",
    "from": [
      354
    ],
    "stone": {
      "ko": "다크펫나이트",
      "sprite": "banettite"
    }
  },
  {
    "id": 10057,
    "base": 359,
    "types": [
      "dark"
    ],
    "power": 1.215,
    "heightM": 1.2,
    "weightKg": 49,
    "kind": "mega",
    "ko": "메가앱솔",
    "en": "Mega Absol",
    "from": [
      359
    ],
    "stone": {
      "ko": "앱솔나이트",
      "sprite": "absolite"
    }
  },
  {
    "id": 10058,
    "base": 445,
    "types": [
      "dragon",
      "ground"
    ],
    "power": 1.167,
    "heightM": 1.9,
    "weightKg": 95,
    "kind": "mega",
    "ko": "메가한카리아스",
    "en": "Mega Garchomp",
    "from": [
      445
    ],
    "stone": {
      "ko": "한카리아스나이트",
      "sprite": "garchompite"
    }
  },
  {
    "id": 10059,
    "base": 448,
    "types": [
      "fighting",
      "steel"
    ],
    "power": 1.19,
    "heightM": 1.3,
    "weightKg": 57.5,
    "kind": "mega",
    "ko": "메가루카리오",
    "en": "Mega Lucario",
    "from": [
      448
    ],
    "stone": {
      "ko": "루카리오나이트",
      "sprite": "lucarionite"
    }
  },
  {
    "id": 10060,
    "base": 460,
    "types": [
      "grass",
      "ice"
    ],
    "power": 1.202,
    "heightM": 2.7,
    "weightKg": 185,
    "kind": "mega",
    "ko": "메가눈설왕",
    "en": "Mega Abomasnow",
    "from": [
      460
    ],
    "stone": {
      "ko": "눈설왕나이트",
      "sprite": "abomasite"
    }
  },
  {
    "id": 10062,
    "base": 380,
    "types": [
      "dragon",
      "psychic"
    ],
    "power": 1.167,
    "heightM": 1.8,
    "weightKg": 52,
    "kind": "mega",
    "ko": "메가라티아스",
    "en": "Mega Latias",
    "from": [
      380
    ],
    "stone": {
      "ko": "라티아스나이트",
      "sprite": "latiasite"
    }
  },
  {
    "id": 10063,
    "base": 381,
    "types": [
      "dragon",
      "psychic"
    ],
    "power": 1.167,
    "heightM": 2.3,
    "weightKg": 70,
    "kind": "mega",
    "ko": "메가라티오스",
    "en": "Mega Latios",
    "from": [
      381
    ],
    "stone": {
      "ko": "라티오스나이트",
      "sprite": "latiosite"
    }
  },
  {
    "id": 10064,
    "base": 260,
    "types": [
      "water",
      "ground"
    ],
    "power": 1.187,
    "heightM": 1.9,
    "weightKg": 102,
    "kind": "mega",
    "ko": "메가대짱이",
    "en": "Mega Swampert",
    "from": [
      260
    ],
    "stone": {
      "ko": "대짱이나이트",
      "sprite": "swampertite"
    }
  },
  {
    "id": 10065,
    "base": 254,
    "types": [
      "grass",
      "dragon"
    ],
    "power": 1.189,
    "heightM": 1.9,
    "weightKg": 55.2,
    "kind": "mega",
    "ko": "메가나무킹",
    "en": "Mega Sceptile",
    "from": [
      254
    ],
    "stone": {
      "ko": "나무킹나이트",
      "sprite": "sceptilite"
    }
  },
  {
    "id": 10066,
    "base": 302,
    "types": [
      "dark",
      "ghost"
    ],
    "power": 1.263,
    "heightM": 0.5,
    "weightKg": 161,
    "kind": "mega",
    "ko": "메가깜까미",
    "en": "Mega Sableye",
    "from": [
      302
    ],
    "stone": {
      "ko": "깜까미나이트",
      "sprite": "sablenite"
    }
  },
  {
    "id": 10067,
    "base": 334,
    "types": [
      "dragon",
      "fairy"
    ],
    "power": 1.204,
    "heightM": 1.5,
    "weightKg": 20.6,
    "kind": "mega",
    "ko": "메가파비코리",
    "en": "Mega Altaria",
    "from": [
      334
    ],
    "stone": {
      "ko": "파비코리나이트",
      "sprite": "altarianite"
    }
  },
  {
    "id": 10068,
    "base": 475,
    "types": [
      "psychic",
      "fighting"
    ],
    "power": 1.193,
    "heightM": 1.6,
    "weightKg": 56.4,
    "kind": "mega",
    "ko": "메가엘레이드",
    "en": "Mega Gallade",
    "from": [
      475
    ],
    "stone": {
      "ko": "엘레이드나이트",
      "sprite": "galladite"
    }
  },
  {
    "id": 10069,
    "base": 531,
    "types": [
      "normal",
      "fairy"
    ],
    "power": 1.225,
    "heightM": 1.5,
    "weightKg": 32,
    "kind": "mega",
    "ko": "메가다부니",
    "en": "Mega Audino",
    "from": [
      531
    ],
    "stone": {
      "ko": "다부니나이트",
      "sprite": "audinite"
    }
  },
  {
    "id": 10070,
    "base": 319,
    "types": [
      "water",
      "dark"
    ],
    "power": 1.217,
    "heightM": 2.5,
    "weightKg": 130.3,
    "kind": "mega",
    "ko": "메가샤크니아",
    "en": "Mega Sharpedo",
    "from": [
      319
    ],
    "stone": {
      "ko": "샤크니아나이트",
      "sprite": "sharpedonite"
    }
  },
  {
    "id": 10071,
    "base": 80,
    "types": [
      "water",
      "psychic"
    ],
    "power": 1.204,
    "heightM": 2,
    "weightKg": 120,
    "kind": "mega",
    "ko": "메가야도란",
    "en": "Mega Slowbro",
    "from": [
      80
    ],
    "stone": {
      "ko": "야도란나이트",
      "sprite": "slowbronite"
    }
  },
  {
    "id": 10072,
    "base": 208,
    "types": [
      "steel",
      "ground"
    ],
    "power": 1.196,
    "heightM": 10.5,
    "weightKg": 740,
    "kind": "mega",
    "ko": "메가강철톤",
    "en": "Mega Steelix",
    "from": [
      208
    ],
    "stone": {
      "ko": "강철톤나이트",
      "sprite": "steelixite"
    }
  },
  {
    "id": 10073,
    "base": 18,
    "types": [
      "normal",
      "flying"
    ],
    "power": 1.209,
    "heightM": 2.2,
    "weightKg": 50.5,
    "kind": "mega",
    "ko": "메가피죤투",
    "en": "Mega Pidgeot",
    "from": [
      18
    ],
    "stone": {
      "ko": "피죤투나이트",
      "sprite": "pidgeotite"
    }
  },
  {
    "id": 10074,
    "base": 362,
    "types": [
      "ice"
    ],
    "power": 1.208,
    "heightM": 2.1,
    "weightKg": 350.2,
    "kind": "mega",
    "ko": "메가얼음귀신",
    "en": "Mega Glalie",
    "from": [
      362
    ],
    "stone": {
      "ko": "얼음귀신나이트",
      "sprite": "glalitite"
    }
  },
  {
    "id": 10075,
    "base": 719,
    "types": [
      "rock",
      "fairy"
    ],
    "power": 1.167,
    "heightM": 1.1,
    "weightKg": 27.8,
    "kind": "mega",
    "ko": "메가디안시",
    "en": "Mega Diancie",
    "from": [
      719
    ],
    "stone": {
      "ko": "디안시나이트",
      "sprite": "diancite"
    }
  },
  {
    "id": 10076,
    "base": 376,
    "types": [
      "steel",
      "psychic"
    ],
    "power": 1.167,
    "heightM": 2.5,
    "weightKg": 942.9,
    "kind": "mega",
    "ko": "메가메타그로스",
    "en": "Mega Metagross",
    "from": [
      376
    ],
    "stone": {
      "ko": "메타그로스나이트",
      "sprite": "metagrossite"
    }
  },
  {
    "id": 10077,
    "base": 382,
    "types": [
      "water"
    ],
    "power": 1.149,
    "heightM": 9.8,
    "weightKg": 430,
    "kind": "mega",
    "ko": "원시가이오가",
    "en": "Mega Kyogre",
    "from": [
      382
    ],
    "stone": {
      "ko": "푸른구슬",
      "sprite": "blue-orb"
    }
  },
  {
    "id": 10078,
    "base": 383,
    "types": [
      "ground",
      "fire"
    ],
    "power": 1.149,
    "heightM": 5,
    "weightKg": 999.7,
    "kind": "mega",
    "ko": "원시그란돈",
    "en": "Mega Groudon",
    "from": [
      383
    ],
    "stone": {
      "ko": "붉은구슬",
      "sprite": "red-orb"
    }
  },
  {
    "id": 10079,
    "base": 384,
    "types": [
      "dragon",
      "flying"
    ],
    "power": 1.147,
    "heightM": 10.8,
    "weightKg": 392,
    "kind": "mega",
    "ko": "메가레쿠쟈",
    "en": "Mega Rayquaza",
    "from": [
      384
    ],
    "stone": {
      "ko": "레쿠쟈나이트",
      "sprite": null
    }
  },
  {
    "id": 10087,
    "base": 323,
    "types": [
      "fire",
      "ground"
    ],
    "power": 1.217,
    "heightM": 2.5,
    "weightKg": 320.5,
    "kind": "mega",
    "ko": "메가폭타",
    "en": "Mega Camerupt",
    "from": [
      323
    ],
    "stone": {
      "ko": "폭타나이트",
      "sprite": "cameruptite"
    }
  },
  {
    "id": 10088,
    "base": 428,
    "types": [
      "normal",
      "fighting"
    ],
    "power": 1.208,
    "heightM": 1.3,
    "weightKg": 28.3,
    "kind": "mega",
    "ko": "메가이어롭",
    "en": "Mega Lopunny",
    "from": [
      428
    ],
    "stone": {
      "ko": "이어롭나이트",
      "sprite": "lopunnite"
    }
  },
  {
    "id": 10089,
    "base": 373,
    "types": [
      "dragon",
      "flying"
    ],
    "power": 1.167,
    "heightM": 1.8,
    "weightKg": 112.6,
    "kind": "mega",
    "ko": "메가보만다",
    "en": "Mega Salamence",
    "from": [
      373
    ],
    "stone": {
      "ko": "보만다나이트",
      "sprite": "salamencite"
    }
  },
  {
    "id": 10090,
    "base": 15,
    "types": [
      "bug",
      "poison"
    ],
    "power": 1.253,
    "heightM": 1.4,
    "weightKg": 40.5,
    "kind": "mega",
    "ko": "메가독침붕",
    "en": "Mega Beedrill",
    "from": [
      15
    ],
    "stone": {
      "ko": "독침붕나이트",
      "sprite": "beedrillite"
    }
  },
  {
    "id": 10155,
    "base": 800,
    "types": [
      "psychic",
      "steel"
    ],
    "power": 1.133,
    "heightM": 3.8,
    "weightKg": 460,
    "kind": "fusion",
    "ko": "네크로즈마(황혼의 갈기)",
    "en": "Dusk Mane",
    "from": [
      800
    ],
    "partner": 791
  },
  {
    "id": 10156,
    "base": 800,
    "types": [
      "psychic",
      "ghost"
    ],
    "power": 1.133,
    "heightM": 4.2,
    "weightKg": 350,
    "kind": "fusion",
    "ko": "네크로즈마(새벽의 날개)",
    "en": "Dawn Wings",
    "from": [
      800
    ],
    "partner": 792
  },
  {
    "id": 10157,
    "base": 800,
    "types": [
      "psychic",
      "dragon"
    ],
    "power": 1.257,
    "heightM": 7.5,
    "weightKg": 230,
    "kind": "mega",
    "ko": "울트라네크로즈마",
    "en": "Ultra Necrozma",
    "from": [
      10155,
      10156
    ]
  },
  {
    "id": 10193,
    "base": 898,
    "types": [
      "psychic",
      "ice"
    ],
    "power": 1.36,
    "heightM": 2.4,
    "weightKg": 809.1,
    "kind": "fusion",
    "ko": "버드렉스(백마 탄 모습)",
    "en": "Ice Rider",
    "from": [
      898
    ],
    "partner": 896
  },
  {
    "id": 10194,
    "base": 898,
    "types": [
      "psychic",
      "ghost"
    ],
    "power": 1.36,
    "heightM": 2.4,
    "weightKg": 53.6,
    "kind": "fusion",
    "ko": "버드렉스(흑마 탄 모습)",
    "en": "Shadow Rider",
    "from": [
      898
    ],
    "partner": 897
  },
  {
    "id": 10195,
    "base": 3,
    "types": [
      "grass",
      "poison"
    ],
    "power": 1,
    "heightM": 24,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 이상해꽃",
    "en": "Gigantamax Venusaur",
    "from": [
      3
    ]
  },
  {
    "id": 10196,
    "base": 6,
    "types": [
      "fire",
      "flying"
    ],
    "power": 1,
    "heightM": 28,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 리자몽",
    "en": "Gigantamax Charizard",
    "from": [
      6
    ]
  },
  {
    "id": 10197,
    "base": 9,
    "types": [
      "water"
    ],
    "power": 1,
    "heightM": 25,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 거북왕",
    "en": "Gigantamax Blastoise",
    "from": [
      9
    ]
  },
  {
    "id": 10198,
    "base": 12,
    "types": [
      "bug",
      "flying"
    ],
    "power": 1,
    "heightM": 17,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 버터플",
    "en": "Gigantamax Butterfree",
    "from": [
      12
    ]
  },
  {
    "id": 10199,
    "base": 25,
    "types": [
      "electric"
    ],
    "power": 1,
    "heightM": 21,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 피카츄",
    "en": "Gigantamax Pikachu",
    "from": [
      25
    ]
  },
  {
    "id": 10200,
    "base": 52,
    "types": [
      "normal"
    ],
    "power": 1,
    "heightM": 33,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 나옹",
    "en": "Gigantamax Meowth",
    "from": [
      52
    ]
  },
  {
    "id": 10201,
    "base": 68,
    "types": [
      "fighting"
    ],
    "power": 1,
    "heightM": 25,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 괴력몬",
    "en": "Gigantamax Machamp",
    "from": [
      68
    ]
  },
  {
    "id": 10202,
    "base": 94,
    "types": [
      "ghost",
      "poison"
    ],
    "power": 1,
    "heightM": 20,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 팬텀",
    "en": "Gigantamax Gengar",
    "from": [
      94
    ]
  },
  {
    "id": 10203,
    "base": 99,
    "types": [
      "water"
    ],
    "power": 1,
    "heightM": 19,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 킹크랩",
    "en": "Gigantamax Kingler",
    "from": [
      99
    ]
  },
  {
    "id": 10204,
    "base": 131,
    "types": [
      "water",
      "ice"
    ],
    "power": 1,
    "heightM": 24,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 라프라스",
    "en": "Gigantamax Lapras",
    "from": [
      131
    ]
  },
  {
    "id": 10205,
    "base": 133,
    "types": [
      "normal"
    ],
    "power": 1,
    "heightM": 18,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 이브이",
    "en": "Gigantamax Eevee",
    "from": [
      133
    ]
  },
  {
    "id": 10206,
    "base": 143,
    "types": [
      "normal"
    ],
    "power": 1,
    "heightM": 35,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 잠만보",
    "en": "Gigantamax Snorlax",
    "from": [
      143
    ]
  },
  {
    "id": 10207,
    "base": 569,
    "types": [
      "poison"
    ],
    "power": 1,
    "heightM": 21,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 더스트나",
    "en": "Gigantamax Garbodor",
    "from": [
      569
    ]
  },
  {
    "id": 10208,
    "base": 809,
    "types": [
      "steel"
    ],
    "power": 1,
    "heightM": 25,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 멜메탈",
    "en": "Gigantamax Melmetal",
    "from": [
      809
    ]
  },
  {
    "id": 10209,
    "base": 812,
    "types": [
      "grass"
    ],
    "power": 1,
    "heightM": 28,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 고릴타",
    "en": "Gigantamax Rillaboom",
    "from": [
      812
    ]
  },
  {
    "id": 10210,
    "base": 815,
    "types": [
      "fire"
    ],
    "power": 1,
    "heightM": 27,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 에이스번",
    "en": "Gigantamax Cinderace",
    "from": [
      815
    ]
  },
  {
    "id": 10211,
    "base": 818,
    "types": [
      "water"
    ],
    "power": 1,
    "heightM": 40,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 인텔리레온",
    "en": "Gigantamax Inteleon",
    "from": [
      818
    ]
  },
  {
    "id": 10212,
    "base": 823,
    "types": [
      "flying",
      "steel"
    ],
    "power": 1,
    "heightM": 14,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 아머까오",
    "en": "Gigantamax Corviknight",
    "from": [
      823
    ]
  },
  {
    "id": 10213,
    "base": 826,
    "types": [
      "bug",
      "psychic"
    ],
    "power": 1,
    "heightM": 14,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 이올브",
    "en": "Gigantamax Orbeetle",
    "from": [
      826
    ]
  },
  {
    "id": 10214,
    "base": 834,
    "types": [
      "water",
      "rock"
    ],
    "power": 1,
    "heightM": 24,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 갈가부기",
    "en": "Gigantamax Drednaw",
    "from": [
      834
    ]
  },
  {
    "id": 10215,
    "base": 839,
    "types": [
      "rock",
      "fire"
    ],
    "power": 1,
    "heightM": 42,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 석탄산",
    "en": "Gigantamax Coalossal",
    "from": [
      839
    ]
  },
  {
    "id": 10216,
    "base": 841,
    "types": [
      "grass",
      "dragon"
    ],
    "power": 1,
    "heightM": 24,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 애프룡",
    "en": "Gigantamax Flapple",
    "from": [
      841
    ]
  },
  {
    "id": 10217,
    "base": 842,
    "types": [
      "grass",
      "dragon"
    ],
    "power": 1,
    "heightM": 24,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 단지래플",
    "en": "Gigantamax Appletun",
    "from": [
      842
    ]
  },
  {
    "id": 10218,
    "base": 844,
    "types": [
      "ground"
    ],
    "power": 1,
    "heightM": 22,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 사다이사",
    "en": "Gigantamax Sandaconda",
    "from": [
      844
    ]
  },
  {
    "id": 10219,
    "base": 849,
    "types": [
      "electric",
      "poison"
    ],
    "power": 1,
    "heightM": 24,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 스트린더",
    "en": "Gigantamax Toxtricity",
    "from": [
      849
    ]
  },
  {
    "id": 10220,
    "base": 851,
    "types": [
      "fire",
      "bug"
    ],
    "power": 1,
    "heightM": 75,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 다태우지네",
    "en": "Gigantamax Centiskorch",
    "from": [
      851
    ]
  },
  {
    "id": 10221,
    "base": 858,
    "types": [
      "psychic",
      "fairy"
    ],
    "power": 1,
    "heightM": 26,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 브리무음",
    "en": "Gigantamax Hatterene",
    "from": [
      858
    ]
  },
  {
    "id": 10222,
    "base": 861,
    "types": [
      "dark",
      "fairy"
    ],
    "power": 1,
    "heightM": 32,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 오롱털",
    "en": "Gigantamax Grimmsnarl",
    "from": [
      861
    ]
  },
  {
    "id": 10223,
    "base": 869,
    "types": [
      "fairy"
    ],
    "power": 1,
    "heightM": 30,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 마휘핑",
    "en": "Gigantamax Alcremie",
    "from": [
      869
    ]
  },
  {
    "id": 10224,
    "base": 879,
    "types": [
      "steel"
    ],
    "power": 1,
    "heightM": 23,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 대왕끼리동",
    "en": "Gigantamax Copperajah",
    "from": [
      879
    ]
  },
  {
    "id": 10225,
    "base": 884,
    "types": [
      "steel",
      "dragon"
    ],
    "power": 1,
    "heightM": 43,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 두랄루돈",
    "en": "Gigantamax Duraludon",
    "from": [
      884
    ]
  },
  {
    "id": 10226,
    "base": 892,
    "types": [
      "fighting",
      "dark"
    ],
    "power": 1,
    "heightM": 29,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 우라오스",
    "en": "Gigantamax Urshifu",
    "from": [
      892
    ]
  },
  {
    "id": 10227,
    "base": 892,
    "types": [
      "fighting",
      "water"
    ],
    "power": 1,
    "heightM": 26,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 우라오스(연격의 태세)",
    "en": "Gigantamax Urshifu",
    "from": [
      892
    ]
  },
  {
    "id": 10228,
    "base": 849,
    "types": [
      "electric",
      "poison"
    ],
    "power": 1,
    "heightM": 24,
    "weightKg": 1000,
    "kind": "gmax",
    "ko": "거다이맥스 스트린더(로우한 모습)",
    "en": "Gigantamax Toxtricity",
    "from": [
      849
    ]
  },
  {
    "id": 10278,
    "base": 36,
    "types": [
      "fairy",
      "flying"
    ],
    "power": 1.207,
    "heightM": 1.7,
    "weightKg": 42.3,
    "kind": "mega",
    "ko": "메가픽시",
    "en": "Mega Clefable",
    "from": [
      36
    ],
    "stone": {
      "ko": "픽시나이트",
      "sprite": null
    }
  },
  {
    "id": 10279,
    "base": 71,
    "types": [
      "grass",
      "poison"
    ],
    "power": 1.204,
    "heightM": 4.5,
    "weightKg": 125.5,
    "kind": "mega",
    "ko": "메가우츠보트",
    "en": "Mega Victreebel",
    "from": [
      71
    ],
    "stone": {
      "ko": "우츠보트나이트",
      "sprite": null
    }
  },
  {
    "id": 10280,
    "base": 121,
    "types": [
      "water",
      "psychic"
    ],
    "power": 1.192,
    "heightM": 2.3,
    "weightKg": 80,
    "kind": "mega",
    "ko": "메가아쿠스타",
    "en": "Mega Starmie",
    "from": [
      121
    ],
    "stone": {
      "ko": "아쿠스타나이트",
      "sprite": null
    }
  },
  {
    "id": 10281,
    "base": 149,
    "types": [
      "dragon",
      "flying"
    ],
    "power": 1.167,
    "heightM": 2.2,
    "weightKg": 290,
    "kind": "mega",
    "ko": "메가망나뇽",
    "en": "Mega Dragonite",
    "from": [
      149
    ],
    "stone": {
      "ko": "망나뇽나이트",
      "sprite": null
    }
  },
  {
    "id": 10282,
    "base": 154,
    "types": [
      "grass",
      "fairy"
    ],
    "power": 1.19,
    "heightM": 2.4,
    "weightKg": 201,
    "kind": "mega",
    "ko": "메가메가니움",
    "en": "Mega Meganium",
    "from": [
      154
    ],
    "stone": {
      "ko": "메가니움나이트",
      "sprite": null
    }
  },
  {
    "id": 10283,
    "base": 160,
    "types": [
      "water",
      "dragon"
    ],
    "power": 1.189,
    "heightM": 2.3,
    "weightKg": 108.8,
    "kind": "mega",
    "ko": "메가장크로다일",
    "en": "Mega Feraligatr",
    "from": [
      160
    ],
    "stone": {
      "ko": "장크로다일나이트",
      "sprite": null
    }
  },
  {
    "id": 10284,
    "base": 227,
    "types": [
      "steel",
      "flying"
    ],
    "power": 1.215,
    "heightM": 1.7,
    "weightKg": 40.4,
    "kind": "mega",
    "ko": "메가무장조",
    "en": "Mega Skarmory",
    "from": [
      227
    ],
    "stone": {
      "ko": "무장조나이트",
      "sprite": null
    }
  },
  {
    "id": 10285,
    "base": 478,
    "types": [
      "ice",
      "ghost"
    ],
    "power": 1.208,
    "heightM": 2.6,
    "weightKg": 29.6,
    "kind": "mega",
    "ko": "메가눈여아",
    "en": "Mega Froslass",
    "from": [
      478
    ],
    "stone": {
      "ko": "눈여아나이트",
      "sprite": null
    }
  },
  {
    "id": 10286,
    "base": 500,
    "types": [
      "fire",
      "fighting"
    ],
    "power": 1.189,
    "heightM": 1.8,
    "weightKg": 180.3,
    "kind": "mega",
    "ko": "메가염무왕",
    "en": "Mega Emboar",
    "from": [
      500
    ],
    "stone": {
      "ko": "염무왕나이트",
      "sprite": null
    }
  },
  {
    "id": 10287,
    "base": 530,
    "types": [
      "ground",
      "steel"
    ],
    "power": 1.197,
    "heightM": 0.9,
    "weightKg": 60,
    "kind": "mega",
    "ko": "메가몰드류",
    "en": "Mega Excadrill",
    "from": [
      530
    ],
    "stone": {
      "ko": "몰드류나이트",
      "sprite": null
    }
  },
  {
    "id": 10288,
    "base": 545,
    "types": [
      "bug",
      "poison"
    ],
    "power": 1.206,
    "heightM": 3.2,
    "weightKg": 230.5,
    "kind": "mega",
    "ko": "메가펜드라",
    "en": "Mega Scolipede",
    "from": [
      545
    ],
    "stone": {
      "ko": "펜드라나이트",
      "sprite": null
    }
  },
  {
    "id": 10289,
    "base": 560,
    "types": [
      "dark",
      "fighting"
    ],
    "power": 1.205,
    "heightM": 1.1,
    "weightKg": 31,
    "kind": "mega",
    "ko": "메가곤율거니",
    "en": "Mega Scrafty",
    "from": [
      560
    ],
    "stone": {
      "ko": "곤율거니나이트",
      "sprite": null
    }
  },
  {
    "id": 10290,
    "base": 604,
    "types": [
      "electric"
    ],
    "power": 1.194,
    "heightM": 3,
    "weightKg": 180,
    "kind": "mega",
    "ko": "메가저리더프",
    "en": "Mega Eelektross",
    "from": [
      604
    ],
    "stone": {
      "ko": "저리더프나이트",
      "sprite": null
    }
  },
  {
    "id": 10291,
    "base": 609,
    "types": [
      "ghost",
      "fire"
    ],
    "power": 1.192,
    "heightM": 2.5,
    "weightKg": 69.6,
    "kind": "mega",
    "ko": "메가샹델라",
    "en": "Mega Chandelure",
    "from": [
      609
    ],
    "stone": {
      "ko": "샹델라나이트",
      "sprite": null
    }
  },
  {
    "id": 10292,
    "base": 652,
    "types": [
      "grass",
      "fighting"
    ],
    "power": 1.189,
    "heightM": 1.6,
    "weightKg": 90,
    "kind": "mega",
    "ko": "메가브리가론",
    "en": "Mega Chesnaught",
    "from": [
      652
    ],
    "stone": {
      "ko": "브리가론나이트",
      "sprite": null
    }
  },
  {
    "id": 10293,
    "base": 655,
    "types": [
      "fire",
      "psychic"
    ],
    "power": 1.187,
    "heightM": 1.5,
    "weightKg": 39,
    "kind": "mega",
    "ko": "메가마폭시",
    "en": "Mega Delphox",
    "from": [
      655
    ],
    "stone": {
      "ko": "마폭시나이트",
      "sprite": null
    }
  },
  {
    "id": 10294,
    "base": 658,
    "types": [
      "water",
      "dark"
    ],
    "power": 1.189,
    "heightM": 1.5,
    "weightKg": 40,
    "kind": "mega",
    "ko": "메가개굴닌자",
    "en": "Mega Greninja",
    "from": [
      658
    ],
    "stone": {
      "ko": "개굴닌자나이트",
      "sprite": null
    }
  },
  {
    "id": 10295,
    "base": 668,
    "types": [
      "fire",
      "normal"
    ],
    "power": 1.197,
    "heightM": 1.5,
    "weightKg": 93.3,
    "kind": "mega",
    "ko": "메가화염레오",
    "en": "Mega Pyroar",
    "from": [
      668
    ],
    "stone": {
      "ko": "화염레오나이트",
      "sprite": null
    }
  },
  {
    "id": 10296,
    "base": 670,
    "types": [
      "fairy"
    ],
    "power": 1.755,
    "heightM": 0.2,
    "weightKg": 100.8,
    "kind": "mega",
    "ko": "메가플라엣테",
    "en": "Mega Floette",
    "from": [
      670
    ],
    "stone": {
      "ko": "플라엣테나이트",
      "sprite": null
    }
  },
  {
    "id": 10297,
    "base": 687,
    "types": [
      "dark",
      "psychic"
    ],
    "power": 1.207,
    "heightM": 2.9,
    "weightKg": 69.8,
    "kind": "mega",
    "ko": "메가칼라마네로",
    "en": "Mega Malamar",
    "from": [
      687
    ],
    "stone": {
      "ko": "칼라마네로나이트",
      "sprite": null
    }
  },
  {
    "id": 10298,
    "base": 689,
    "types": [
      "rock",
      "fighting"
    ],
    "power": 1.2,
    "heightM": 2.2,
    "weightKg": 100,
    "kind": "mega",
    "ko": "메가거북손데스",
    "en": "Mega Barbaracle",
    "from": [
      689
    ],
    "stone": {
      "ko": "거북손데스나이트",
      "sprite": null
    }
  },
  {
    "id": 10299,
    "base": 691,
    "types": [
      "poison",
      "dragon"
    ],
    "power": 1.202,
    "heightM": 2.1,
    "weightKg": 100.3,
    "kind": "mega",
    "ko": "메가드래캄",
    "en": "Mega Dragalge",
    "from": [
      691
    ],
    "stone": {
      "ko": "드래캄나이트",
      "sprite": null
    }
  },
  {
    "id": 10300,
    "base": 701,
    "types": [
      "fighting",
      "flying"
    ],
    "power": 1.2,
    "heightM": 1,
    "weightKg": 25,
    "kind": "mega",
    "ko": "메가루차불",
    "en": "Mega Hawlucha",
    "from": [
      701
    ],
    "stone": {
      "ko": "루차불나이트",
      "sprite": null
    }
  },
  {
    "id": 10301,
    "base": 718,
    "types": [
      "dragon",
      "ground"
    ],
    "power": 1.297,
    "heightM": 7.7,
    "weightKg": 610,
    "kind": "mega",
    "ko": "메가지가르데",
    "en": "Mega Zygarde",
    "from": [
      718
    ],
    "stone": {
      "ko": "지가르데나이트",
      "sprite": null
    }
  },
  {
    "id": 10302,
    "base": 780,
    "types": [
      "normal",
      "dragon"
    ],
    "power": 1.206,
    "heightM": 3,
    "weightKg": 240.5,
    "kind": "mega",
    "ko": "메가할비롱",
    "en": "Mega Drampa",
    "from": [
      780
    ],
    "stone": {
      "ko": "할비롱나이트",
      "sprite": null
    }
  },
  {
    "id": 10303,
    "base": 870,
    "types": [
      "fighting"
    ],
    "power": 1.213,
    "heightM": 1.6,
    "weightKg": 99,
    "kind": "mega",
    "ko": "메가대여르",
    "en": "Mega Falinks",
    "from": [
      870
    ],
    "stone": {
      "ko": "대여르나이트",
      "sprite": null
    }
  },
  {
    "id": 10304,
    "base": 26,
    "types": [
      "electric"
    ],
    "power": 1.206,
    "heightM": 1.2,
    "weightKg": 38,
    "kind": "mega",
    "ko": "메가라이츄X",
    "en": "Mega Raichu X",
    "from": [
      26
    ],
    "stone": {
      "ko": "라이츄나이트X",
      "sprite": null
    }
  },
  {
    "id": 10305,
    "base": 26,
    "types": [
      "electric"
    ],
    "power": 1.206,
    "heightM": 1,
    "weightKg": 26,
    "kind": "mega",
    "ko": "메가라이츄Y",
    "en": "Mega Raichu Y",
    "from": [
      26
    ],
    "stone": {
      "ko": "라이츄나이트Y",
      "sprite": null
    }
  },
  {
    "id": 10306,
    "base": 358,
    "types": [
      "psychic",
      "steel"
    ],
    "power": 1.22,
    "heightM": 1.2,
    "weightKg": 8,
    "kind": "mega",
    "ko": "메가치렁",
    "en": "Mega Chimecho",
    "from": [
      358
    ],
    "stone": {
      "ko": "치렁나이트",
      "sprite": null
    }
  },
  {
    "id": 10307,
    "base": 359,
    "types": [
      "dark",
      "ghost"
    ],
    "power": 1.215,
    "heightM": 1.2,
    "weightKg": 49,
    "kind": "mega",
    "ko": "메가앱솔Z",
    "en": "Mega Absol Z",
    "from": [
      359
    ],
    "stone": {
      "ko": "앱솔나이트Z",
      "sprite": null
    }
  },
  {
    "id": 10308,
    "base": 398,
    "types": [
      "fighting",
      "flying"
    ],
    "power": 1.206,
    "heightM": 1.9,
    "weightKg": 50,
    "kind": "mega",
    "ko": "메가찌르호크",
    "en": "Mega Staraptor",
    "from": [
      398
    ],
    "stone": {
      "ko": "찌르호크나이트",
      "sprite": null
    }
  },
  {
    "id": 10309,
    "base": 445,
    "types": [
      "dragon"
    ],
    "power": 1.167,
    "heightM": 1.9,
    "weightKg": 99,
    "kind": "mega",
    "ko": "메가한카리아스Z",
    "en": "Mega Garchomp Z",
    "from": [
      445
    ],
    "stone": {
      "ko": "한카리아스나이트Z",
      "sprite": null
    }
  },
  {
    "id": 10310,
    "base": 448,
    "types": [
      "fighting",
      "steel"
    ],
    "power": 1.19,
    "heightM": 1.3,
    "weightKg": 49.4,
    "kind": "mega",
    "ko": "메가루카리오Z",
    "en": "Mega Lucario Z",
    "from": [
      448
    ],
    "stone": {
      "ko": "루카리오나이트Z",
      "sprite": null
    }
  },
  {
    "id": 10311,
    "base": 485,
    "types": [
      "fire",
      "steel"
    ],
    "power": 1.167,
    "heightM": 2.8,
    "weightKg": 570,
    "kind": "mega",
    "ko": "메가히드런",
    "en": "Mega Heatran",
    "from": [
      485
    ],
    "stone": {
      "ko": "히드런나이트",
      "sprite": null
    }
  },
  {
    "id": 10312,
    "base": 491,
    "types": [
      "dark"
    ],
    "power": 1.167,
    "heightM": 3,
    "weightKg": 240,
    "kind": "mega",
    "ko": "메가다크라이",
    "en": "Mega Darkrai",
    "from": [
      491
    ],
    "stone": {
      "ko": "다크라이나이트",
      "sprite": null
    }
  },
  {
    "id": 10313,
    "base": 623,
    "types": [
      "ground",
      "ghost"
    ],
    "power": 1.207,
    "heightM": 4,
    "weightKg": 330,
    "kind": "mega",
    "ko": "메가골루그",
    "en": "Mega Golurk",
    "from": [
      623
    ],
    "stone": {
      "ko": "골루그나이트",
      "sprite": null
    }
  },
  {
    "id": 10314,
    "base": 678,
    "types": [
      "psychic"
    ],
    "power": 1.215,
    "heightM": 0.8,
    "weightKg": 10.1,
    "kind": "mega",
    "ko": "메가냐오닉스♂",
    "en": "Mega Meowstic",
    "from": [
      678
    ],
    "stone": {
      "ko": "냐오닉스나이트♂",
      "sprite": null
    }
  },
  {
    "id": 10315,
    "base": 740,
    "types": [
      "fighting",
      "ice"
    ],
    "power": 1.209,
    "heightM": 2.6,
    "weightKg": 252.8,
    "kind": "mega",
    "ko": "메가모단단게",
    "en": "Mega Crabominable",
    "from": [
      740
    ],
    "stone": {
      "ko": "모단단게나이트",
      "sprite": null
    }
  },
  {
    "id": 10316,
    "base": 768,
    "types": [
      "bug",
      "steel"
    ],
    "power": 1.189,
    "heightM": 2.3,
    "weightKg": 148,
    "kind": "mega",
    "ko": "메가갑주무사",
    "en": "Mega Golisopod",
    "from": [
      768
    ],
    "stone": {
      "ko": "갑주무사나이트",
      "sprite": null
    }
  },
  {
    "id": 10317,
    "base": 801,
    "types": [
      "steel",
      "fairy"
    ],
    "power": 1.167,
    "heightM": 1.3,
    "weightKg": 248.1,
    "kind": "mega",
    "ko": "메가마기아나",
    "en": "Mega Magearna",
    "from": [
      801
    ],
    "stone": {
      "ko": "마기아나나이트",
      "sprite": null
    }
  },
  {
    "id": 10318,
    "base": 801,
    "types": [
      "steel",
      "fairy"
    ],
    "power": 1.167,
    "heightM": 1.3,
    "weightKg": 248.1,
    "kind": "mega",
    "ko": "메가마기아나(500년 전의 색)",
    "en": "Mega Original Magearna",
    "from": [
      801
    ],
    "stone": {
      "ko": "마기아나나이트(500년 전의 색)",
      "sprite": null
    }
  },
  {
    "id": 10319,
    "base": 807,
    "types": [
      "electric"
    ],
    "power": 1.167,
    "heightM": 1.5,
    "weightKg": 44.5,
    "kind": "mega",
    "ko": "메가제라오라",
    "en": "Mega Zeraora",
    "from": [
      807
    ],
    "stone": {
      "ko": "제라오라나이트",
      "sprite": null
    }
  },
  {
    "id": 10320,
    "base": 952,
    "types": [
      "grass",
      "fire"
    ],
    "power": 1.206,
    "heightM": 1.2,
    "weightKg": 22,
    "kind": "mega",
    "ko": "메가스코빌런",
    "en": "Mega Scovillain",
    "from": [
      952
    ],
    "stone": {
      "ko": "스코빌런나이트",
      "sprite": null
    }
  },
  {
    "id": 10321,
    "base": 970,
    "types": [
      "rock",
      "poison"
    ],
    "power": 1.19,
    "heightM": 2.8,
    "weightKg": 77,
    "kind": "mega",
    "ko": "메가킬라플로르",
    "en": "Mega Glimmora",
    "from": [
      970
    ],
    "stone": {
      "ko": "킬라플로르나이트",
      "sprite": null
    }
  },
  {
    "id": 10322,
    "base": 978,
    "types": [
      "dragon",
      "water"
    ],
    "power": 1.211,
    "heightM": 0.6,
    "weightKg": 24,
    "kind": "mega",
    "ko": "메가싸리용(말린 모습)",
    "en": "Mega Curly Tatsugiri",
    "from": [
      978
    ],
    "stone": {
      "ko": "싸리용나이트(말린 모습)",
      "sprite": null
    }
  },
  {
    "id": 10323,
    "base": 978,
    "types": [
      "dragon",
      "water"
    ],
    "power": 1.211,
    "heightM": 0.6,
    "weightKg": 24,
    "kind": "mega",
    "ko": "메가싸리용(늘어진 모습)",
    "en": "Mega Droopy Tatsugiri",
    "from": [
      978
    ],
    "stone": {
      "ko": "싸리용나이트(늘어진 모습)",
      "sprite": null
    }
  },
  {
    "id": 10324,
    "base": 978,
    "types": [
      "dragon",
      "water"
    ],
    "power": 1.211,
    "heightM": 0.6,
    "weightKg": 24,
    "kind": "mega",
    "ko": "메가싸리용(쭉 편 모습)",
    "en": "Mega Stretchy Tatsugiri",
    "from": [
      978
    ],
    "stone": {
      "ko": "싸리용나이트(쭉 편 모습)",
      "sprite": null
    }
  },
  {
    "id": 10325,
    "base": 998,
    "types": [
      "dragon",
      "ice"
    ],
    "power": 1.167,
    "heightM": 2.1,
    "weightKg": 315,
    "kind": "mega",
    "ko": "메가드닐레이브",
    "en": "Mega Baxcalibur",
    "from": [
      998
    ],
    "stone": {
      "ko": "드닐레이브나이트",
      "sprite": null
    }
  },
  {
    "id": 10326,
    "base": 678,
    "types": [
      "psychic"
    ],
    "power": 1.215,
    "heightM": 0.8,
    "weightKg": 10.1,
    "kind": "mega",
    "ko": "메가냐오닉스♀",
    "en": "Mega Meowstic",
    "from": [
      678
    ],
    "stone": {
      "ko": "냐오닉스나이트♀",
      "sprite": null
    }
  }
] as Form[];

const BY_ID = new Map(FORMS.map((f) => [f.id, f]));

export function formById(id: number): Form | null {
  return BY_ID.get(id) ?? null;
}

/**
 * display id -> the forms reachable from it.
 *
 * Keyed by display id rather than by species precisely so a fused Necrozma can
 * offer Ultra Burst while a plain one cannot.
 */
const FROM = (() => {
  const m = new Map<number, Form[]>();
  for (const f of FORMS) {
    for (const src of f.from) {
      if (!m.has(src)) m.set(src, []);
      m.get(src)!.push(f);
    }
  }
  return m;
})();

export function formsFrom(displayId: number): Form[] {
  return FROM.get(displayId) ?? [];
}
