// GENERATED by scripts/gen-legends.ts — do not edit by hand.
// Source: PokeAPI (https://pokeapi.co). Legendary and mythical species, and the
// signature items the games gate them behind.
// Sprites themselves are never bundled; they are fetched at runtime.

/**
 * One legendary or mythical species.
 *
 * `myth` is PokeAPI's `is_mythical`. Everything here that is not mythical is
 * legendary — the query asks for nothing else — so the two together are the
 * classification `rarityOfSpecies` cannot give (it reads capture_rate, which
 * calls Necrozma common and Ditto legendary).
 *
 * There is no gate in this file. Which condition opens which species is a
 * design decision and lives in server/legends.ts, hand-written.
 */
export type LegendRow = { id: number; ko: string; myth: boolean; gen: number };

export const LEGENDS: LegendRow[] = [
  {
    "id": 144,
    "ko": "프리져",
    "myth": false,
    "gen": 1
  },
  {
    "id": 145,
    "ko": "썬더",
    "myth": false,
    "gen": 1
  },
  {
    "id": 146,
    "ko": "파이어",
    "myth": false,
    "gen": 1
  },
  {
    "id": 150,
    "ko": "뮤츠",
    "myth": false,
    "gen": 1
  },
  {
    "id": 151,
    "ko": "뮤",
    "myth": true,
    "gen": 1
  },
  {
    "id": 243,
    "ko": "라이코",
    "myth": false,
    "gen": 2
  },
  {
    "id": 244,
    "ko": "앤테이",
    "myth": false,
    "gen": 2
  },
  {
    "id": 245,
    "ko": "스이쿤",
    "myth": false,
    "gen": 2
  },
  {
    "id": 249,
    "ko": "루기아",
    "myth": false,
    "gen": 2
  },
  {
    "id": 250,
    "ko": "칠색조",
    "myth": false,
    "gen": 2
  },
  {
    "id": 251,
    "ko": "세레비",
    "myth": true,
    "gen": 2
  },
  {
    "id": 377,
    "ko": "레지락",
    "myth": false,
    "gen": 3
  },
  {
    "id": 378,
    "ko": "레지아이스",
    "myth": false,
    "gen": 3
  },
  {
    "id": 379,
    "ko": "레지스틸",
    "myth": false,
    "gen": 3
  },
  {
    "id": 380,
    "ko": "라티아스",
    "myth": false,
    "gen": 3
  },
  {
    "id": 381,
    "ko": "라티오스",
    "myth": false,
    "gen": 3
  },
  {
    "id": 382,
    "ko": "가이오가",
    "myth": false,
    "gen": 3
  },
  {
    "id": 383,
    "ko": "그란돈",
    "myth": false,
    "gen": 3
  },
  {
    "id": 384,
    "ko": "레쿠쟈",
    "myth": false,
    "gen": 3
  },
  {
    "id": 385,
    "ko": "지라치",
    "myth": true,
    "gen": 3
  },
  {
    "id": 386,
    "ko": "테오키스",
    "myth": true,
    "gen": 3
  },
  {
    "id": 480,
    "ko": "유크시",
    "myth": false,
    "gen": 4
  },
  {
    "id": 481,
    "ko": "엠라이트",
    "myth": false,
    "gen": 4
  },
  {
    "id": 482,
    "ko": "아그놈",
    "myth": false,
    "gen": 4
  },
  {
    "id": 483,
    "ko": "디아루가",
    "myth": false,
    "gen": 4
  },
  {
    "id": 484,
    "ko": "펄기아",
    "myth": false,
    "gen": 4
  },
  {
    "id": 485,
    "ko": "히드런",
    "myth": false,
    "gen": 4
  },
  {
    "id": 486,
    "ko": "레지기가스",
    "myth": false,
    "gen": 4
  },
  {
    "id": 487,
    "ko": "기라티나",
    "myth": false,
    "gen": 4
  },
  {
    "id": 488,
    "ko": "크레세리아",
    "myth": false,
    "gen": 4
  },
  {
    "id": 489,
    "ko": "피오네",
    "myth": true,
    "gen": 4
  },
  {
    "id": 490,
    "ko": "마나피",
    "myth": true,
    "gen": 4
  },
  {
    "id": 491,
    "ko": "다크라이",
    "myth": true,
    "gen": 4
  },
  {
    "id": 492,
    "ko": "쉐이미",
    "myth": true,
    "gen": 4
  },
  {
    "id": 493,
    "ko": "아르세우스",
    "myth": true,
    "gen": 4
  },
  {
    "id": 494,
    "ko": "비크티니",
    "myth": true,
    "gen": 5
  },
  {
    "id": 638,
    "ko": "코바르온",
    "myth": false,
    "gen": 5
  },
  {
    "id": 639,
    "ko": "테라키온",
    "myth": false,
    "gen": 5
  },
  {
    "id": 640,
    "ko": "비리디온",
    "myth": false,
    "gen": 5
  },
  {
    "id": 641,
    "ko": "토네로스",
    "myth": false,
    "gen": 5
  },
  {
    "id": 642,
    "ko": "볼트로스",
    "myth": false,
    "gen": 5
  },
  {
    "id": 643,
    "ko": "레시라무",
    "myth": false,
    "gen": 5
  },
  {
    "id": 644,
    "ko": "제크로무",
    "myth": false,
    "gen": 5
  },
  {
    "id": 645,
    "ko": "랜드로스",
    "myth": false,
    "gen": 5
  },
  {
    "id": 646,
    "ko": "큐레무",
    "myth": false,
    "gen": 5
  },
  {
    "id": 647,
    "ko": "케르디오",
    "myth": true,
    "gen": 5
  },
  {
    "id": 648,
    "ko": "메로엣타",
    "myth": true,
    "gen": 5
  },
  {
    "id": 649,
    "ko": "게노세크트",
    "myth": true,
    "gen": 5
  },
  {
    "id": 716,
    "ko": "제르네아스",
    "myth": false,
    "gen": 6
  },
  {
    "id": 717,
    "ko": "이벨타르",
    "myth": false,
    "gen": 6
  },
  {
    "id": 718,
    "ko": "지가르데",
    "myth": false,
    "gen": 6
  },
  {
    "id": 719,
    "ko": "디안시",
    "myth": true,
    "gen": 6
  },
  {
    "id": 720,
    "ko": "후파",
    "myth": true,
    "gen": 6
  },
  {
    "id": 721,
    "ko": "볼케니온",
    "myth": true,
    "gen": 6
  },
  {
    "id": 772,
    "ko": "타입:널",
    "myth": false,
    "gen": 7
  },
  {
    "id": 773,
    "ko": "실버디",
    "myth": false,
    "gen": 7
  },
  {
    "id": 785,
    "ko": "카푸꼬꼬꼭",
    "myth": false,
    "gen": 7
  },
  {
    "id": 786,
    "ko": "카푸나비나",
    "myth": false,
    "gen": 7
  },
  {
    "id": 787,
    "ko": "카푸브루루",
    "myth": false,
    "gen": 7
  },
  {
    "id": 788,
    "ko": "카푸느지느",
    "myth": false,
    "gen": 7
  },
  {
    "id": 789,
    "ko": "코스모그",
    "myth": false,
    "gen": 7
  },
  {
    "id": 790,
    "ko": "코스모움",
    "myth": false,
    "gen": 7
  },
  {
    "id": 791,
    "ko": "솔가레오",
    "myth": false,
    "gen": 7
  },
  {
    "id": 792,
    "ko": "루나아라",
    "myth": false,
    "gen": 7
  },
  {
    "id": 800,
    "ko": "네크로즈마",
    "myth": false,
    "gen": 7
  },
  {
    "id": 801,
    "ko": "마기아나",
    "myth": true,
    "gen": 7
  },
  {
    "id": 802,
    "ko": "마샤도",
    "myth": true,
    "gen": 7
  },
  {
    "id": 807,
    "ko": "제라오라",
    "myth": true,
    "gen": 7
  },
  {
    "id": 808,
    "ko": "멜탄",
    "myth": true,
    "gen": 7
  },
  {
    "id": 809,
    "ko": "멜메탈",
    "myth": true,
    "gen": 7
  },
  {
    "id": 888,
    "ko": "자시안",
    "myth": false,
    "gen": 8
  },
  {
    "id": 889,
    "ko": "자마젠타",
    "myth": false,
    "gen": 8
  },
  {
    "id": 890,
    "ko": "무한다이노",
    "myth": false,
    "gen": 8
  },
  {
    "id": 891,
    "ko": "치고마",
    "myth": false,
    "gen": 8
  },
  {
    "id": 892,
    "ko": "우라오스",
    "myth": false,
    "gen": 8
  },
  {
    "id": 893,
    "ko": "자루도",
    "myth": true,
    "gen": 8
  },
  {
    "id": 894,
    "ko": "레지에레키",
    "myth": false,
    "gen": 8
  },
  {
    "id": 895,
    "ko": "레지드래고",
    "myth": false,
    "gen": 8
  },
  {
    "id": 896,
    "ko": "블리자포스",
    "myth": false,
    "gen": 8
  },
  {
    "id": 897,
    "ko": "레이스포스",
    "myth": false,
    "gen": 8
  },
  {
    "id": 898,
    "ko": "버드렉스",
    "myth": false,
    "gen": 8
  },
  {
    "id": 905,
    "ko": "러브로스",
    "myth": false,
    "gen": 8
  },
  {
    "id": 1001,
    "ko": "총지엔",
    "myth": false,
    "gen": 9
  },
  {
    "id": 1002,
    "ko": "파오젠",
    "myth": false,
    "gen": 9
  },
  {
    "id": 1003,
    "ko": "딩루",
    "myth": false,
    "gen": 9
  },
  {
    "id": 1004,
    "ko": "위유이",
    "myth": false,
    "gen": 9
  },
  {
    "id": 1007,
    "ko": "코라이돈",
    "myth": false,
    "gen": 9
  },
  {
    "id": 1008,
    "ko": "미라이돈",
    "myth": false,
    "gen": 9
  },
  {
    "id": 1014,
    "ko": "조타구",
    "myth": false,
    "gen": 9
  },
  {
    "id": 1015,
    "ko": "이야후",
    "myth": false,
    "gen": 9
  },
  {
    "id": 1016,
    "ko": "기로치",
    "myth": false,
    "gen": 9
  },
  {
    "id": 1017,
    "ko": "오거폰",
    "myth": false,
    "gen": 9
  },
  {
    "id": 1024,
    "ko": "테라파고스",
    "myth": false,
    "gen": 9
  },
  {
    "id": 1025,
    "ko": "복숭악동",
    "myth": true,
    "gen": 9
  }
];

/** speciesId -> row, for the O(1) test every encounter does. */
const BY_ID = new Map(LEGENDS.map((l) => [l.id, l]));

/** Is this species gated at all? The one question the hunt loop asks. */
export function legendOf(speciesId: number): LegendRow | null {
  return BY_ID.get(speciesId) ?? null;
}

/**
 * A signature item.
 *
 * `sprite` is the PokeAPI slug, or null where the sprite repository has no
 * icon — it thins out around Gen 7, so the Rusted Sword and the masks have
 * none. The bag draws a glyph for those, exactly as it does for the Dynamax
 * Band.
 */
export type LegendItem = { slug: string; ko: string; sprite: string | null };

export const LEGEND_ITEMS: LegendItem[] = [
  {
    "slug": "adamant-orb",
    "ko": "금강옥",
    "sprite": "adamant-orb"
  },
  {
    "slug": "auspicious-armor",
    "ko": "축복받은갑옷",
    "sprite": null
  },
  {
    "slug": "azure-flute",
    "ko": "천계의피리",
    "sprite": "azure-flute"
  },
  {
    "slug": "blue-orb",
    "ko": "쪽빛구슬",
    "sprite": "blue-orb"
  },
  {
    "slug": "clear-amulet",
    "ko": "클리어참",
    "sprite": "clear-amulet"
  },
  {
    "slug": "clear-bell",
    "ko": "크리스탈방울",
    "sprite": "clear-bell"
  },
  {
    "slug": "cornerstone-mask",
    "ko": "주춧돌의가면",
    "sprite": "cornerstone-mask"
  },
  {
    "slug": "dark-stone",
    "ko": "다크스톤",
    "sprite": "dark-stone"
  },
  {
    "slug": "enigma-stone",
    "ko": "수수께끼의수정",
    "sprite": "enigma-stone"
  },
  {
    "slug": "gracidea",
    "ko": "그라시데아꽃",
    "sprite": "gracidea"
  },
  {
    "slug": "griseous-orb",
    "ko": "백금옥",
    "sprite": "griseous-orb"
  },
  {
    "slug": "hearthflame-mask",
    "ko": "화덕의가면",
    "sprite": "hearthflame-mask"
  },
  {
    "slug": "light-stone",
    "ko": "라이트스톤",
    "sprite": "light-stone"
  },
  {
    "slug": "lunar-wing",
    "ko": "초승달깃털",
    "sprite": "lunar-wing"
  },
  {
    "slug": "lustrous-orb",
    "ko": "백옥",
    "sprite": "lustrous-orb"
  },
  {
    "slug": "magma-stone",
    "ko": "화산의돌",
    "sprite": "magma-stone"
  },
  {
    "slug": "malicious-armor",
    "ko": "저주받은갑옷",
    "sprite": null
  },
  {
    "slug": "member-card",
    "ko": "멤버스카드",
    "sprite": "member-card"
  },
  {
    "slug": "meteorite",
    "ko": "운석",
    "sprite": "meteorite"
  },
  {
    "slug": "moon-flute",
    "ko": "달의피리",
    "sprite": "moon-flute"
  },
  {
    "slug": "n-lunarizer--merge",
    "ko": "네크로플러스루나",
    "sprite": "n-lunarizer--merge"
  },
  {
    "slug": "n-solarizer--merge",
    "ko": "네크로플러스솔",
    "sprite": "n-solarizer--merge"
  },
  {
    "slug": "oaks-letter",
    "ko": "오박사의편지",
    "sprite": "oaks-letter"
  },
  {
    "slug": "odd-keystone",
    "ko": "쐐기돌",
    "sprite": "odd-keystone"
  },
  {
    "slug": "prison-bottle",
    "ko": "굴레의항아리",
    "sprite": "prison-bottle"
  },
  {
    "slug": "rainbow-wing",
    "ko": "무지갯빛깃털",
    "sprite": "rainbow-wing"
  },
  {
    "slug": "red-orb",
    "ko": "주홍구슬",
    "sprite": "red-orb"
  },
  {
    "slug": "reins-of-unity",
    "ko": "유대의고삐",
    "sprite": "reins-of-unity"
  },
  {
    "slug": "reveal-glass",
    "ko": "비추는거울",
    "sprite": "reveal-glass"
  },
  {
    "slug": "rusted-shield",
    "ko": "녹슨방패",
    "sprite": "rusted-shield"
  },
  {
    "slug": "rusted-sword",
    "ko": "녹슨검",
    "sprite": "rusted-sword"
  },
  {
    "slug": "scroll-of-darkness",
    "ko": "악의 족자",
    "sprite": null
  },
  {
    "slug": "scroll-of-waters",
    "ko": "물의 족자",
    "sprite": null
  },
  {
    "slug": "silver-wing",
    "ko": "은빛깃털",
    "sprite": "silver-wing"
  },
  {
    "slug": "soul-dew",
    "ko": "마음의물방울",
    "sprite": "soul-dew"
  },
  {
    "slug": "sun-flute",
    "ko": "태양의피리",
    "sprite": "sun-flute"
  },
  {
    "slug": "tidal-bell",
    "ko": "해명의방울",
    "sprite": "tidal-bell"
  },
  {
    "slug": "wellspring-mask",
    "ko": "우물의가면",
    "sprite": "wellspring-mask"
  }
];

const ITEM_BY_SLUG = new Map(LEGEND_ITEMS.map((i) => [i.slug, i]));

export function legendItem(slug: string): LegendItem | null {
  return ITEM_BY_SLUG.get(slug) ?? null;
}
