// GENERATED by scripts/gen-journey.ts — do not edit by hand.
// Source: PokeAPI (https://pokeapi.co) for regions and for Hoenn/Kalos/Alola
// place names; the rest are hand-checked in the generator. See that file.

import type { TerrainId } from './terrain.ts';

/**
 * Every backdrop the journey can ask for at the horizon.
 *
 * A subset of server/biome.ts's BG_SLUGS, which is the authority on what
 * actually exists upstream. Declared here rather than imported because this
 * file is renderer-side and that one is not — a test keeps the two in step.
 */
export type SkyId = 'beach' | 'beachshore' | 'city' | 'dampcave' | 'desert' | 'earthycave' | 'forest' | 'icecave' | 'meadow' | 'mountain' | 'river' | 'thunderplains' | 'volcanocave';

/**
 * One place on the journey, and the two independent things it looks like.
 *
 * `terrain` is which of the ten sheets gets painted underfoot. It is NOT what
 * the place is — a town and a stone road walk on the same cobble, and the
 * sheets have to cover 240 places between them.
 *
 * `sky` is the Gen-5 backdrop hung at the horizon, or null for nowhere in
 * particular. It is classified separately because the two layers have different
 * limits: sheets are capped by what CC0 art exists, backdrops are not, so a
 * desert can have a sky without having a floor.
 */
export type Stop = { ko: string; region: string; terrain: TerrainId; sky: SkyId | null };

export const STOPS: Stop[] = [
 {
  "ko": "태초마을",
  "region": "관동",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "상록시티",
  "region": "관동",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "상록숲",
  "region": "관동",
  "terrain": "forest",
  "sky": "forest"
 },
 {
  "ko": "회색시티",
  "region": "관동",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "달맞이산",
  "region": "관동",
  "terrain": "mountain",
  "sky": "mountain"
 },
 {
  "ko": "블루시티",
  "region": "관동",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "갈색시티",
  "region": "관동",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "디그다굴",
  "region": "관동",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "바위굴",
  "region": "관동",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "보라타운",
  "region": "관동",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "포켓몬타워",
  "region": "관동",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "무지개시티",
  "region": "관동",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "무인발전소",
  "region": "관동",
  "terrain": "field",
  "sky": "thunderplains"
 },
 {
  "ko": "노랑시티",
  "region": "관동",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "연분홍시티",
  "region": "관동",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "사파리존",
  "region": "관동",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "홍련섬",
  "region": "관동",
  "terrain": "seaside",
  "sky": "beach"
 },
 {
  "ko": "포켓몬저택",
  "region": "관동",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "쌍둥이섬",
  "region": "관동",
  "terrain": "seaside",
  "sky": "beach"
 },
 {
  "ko": "석영고원",
  "region": "관동",
  "terrain": "mountain",
  "sky": "mountain"
 },
 {
  "ko": "연두마을",
  "region": "성도",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "무궁시티",
  "region": "성도",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "도라지시티",
  "region": "성도",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "방울탑",
  "region": "성도",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "알프의유적",
  "region": "성도",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "뭉게숲",
  "region": "성도",
  "terrain": "forest",
  "sky": "forest"
 },
 {
  "ko": "고동마을",
  "region": "성도",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "어둠의동굴",
  "region": "성도",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "금빛시티",
  "region": "성도",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "국립공원",
  "region": "성도",
  "terrain": "flowers",
  "sky": "meadow"
 },
 {
  "ko": "인주시티",
  "region": "성도",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "타버린탑",
  "region": "성도",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "담청시티",
  "region": "성도",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "초옥시티",
  "region": "성도",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "황토마을",
  "region": "성도",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "분노의호수",
  "region": "성도",
  "terrain": "lakeside",
  "sky": "river"
 },
 {
  "ko": "얼음길",
  "region": "성도",
  "terrain": "cave",
  "sky": "icecave"
 },
 {
  "ko": "검은먹시티",
  "region": "성도",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "용의굴",
  "region": "성도",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "소용돌이섬",
  "region": "성도",
  "terrain": "seaside",
  "sky": "beach"
 },
 {
  "ko": "은빛산",
  "region": "성도",
  "terrain": "mountain",
  "sky": "mountain"
 },
 {
  "ko": "등화도시",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "잿빛도시",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "해안시티",
  "region": "호연",
  "terrain": "seaside",
  "sky": "beachshore"
 },
 {
  "ko": "이끼시티",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "루네시티",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "그랜드시티",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "유성의 폭포",
  "region": "호연",
  "terrain": "lakeside",
  "sky": "river"
 },
 {
  "ko": "금잔터널",
  "region": "호연",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "바위 동굴",
  "region": "호연",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "등화숲",
  "region": "호연",
  "terrain": "forest",
  "sky": "forest"
 },
 {
  "ko": "울퉁불퉁 산길",
  "region": "호연",
  "terrain": "mountain",
  "sky": "mountain"
 },
 {
  "ko": "불꽃샛길",
  "region": "호연",
  "terrain": "flowers",
  "sky": "meadow"
 },
 {
  "ko": "송화산",
  "region": "호연",
  "terrain": "mountain",
  "sky": "volcanocave"
 },
 {
  "ko": "해저동굴",
  "region": "호연",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "각성의 사당",
  "region": "호연",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "챔피언로드",
  "region": "호연",
  "terrain": "stonepath",
  "sky": null
 },
 {
  "ko": "여울의 동굴",
  "region": "호연",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "뉴보라",
  "region": "호연",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "하늘기둥",
  "region": "호연",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "사파리존",
  "region": "호연",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "무로마을",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "황금마을",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "미로마을",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "고도마을",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "용암마을",
  "region": "호연",
  "terrain": "town",
  "sky": "volcanocave"
 },
 {
  "ko": "단풍마을",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "잔디마을",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "보라시티",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "금탄도시",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "검방울시티",
  "region": "호연",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "굴뚝산",
  "region": "호연",
  "terrain": "mountain",
  "sky": "mountain"
 },
 {
  "ko": "환상섬",
  "region": "호연",
  "terrain": "seaside",
  "sky": "beach"
 },
 {
  "ko": "남쪽의 외딴섬",
  "region": "호연",
  "terrain": "seaside",
  "sky": "beach"
 },
 {
  "ko": "고시의 석실",
  "region": "호연",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "가뭄의 암굴",
  "region": "호연",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "작은 섬 옆굴",
  "region": "호연",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "사막유적",
  "region": "호연",
  "terrain": "desert",
  "sky": "desert"
 },
 {
  "ko": "고대의 무덤",
  "region": "호연",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "비밀기지",
  "region": "호연",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "포켓몬리그",
  "region": "호연",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "아쿠아단아지트",
  "region": "호연",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "씨보라",
  "region": "호연",
  "terrain": "seaside",
  "sky": "beach"
 },
 {
  "ko": "마그마단아지트",
  "region": "호연",
  "terrain": "field",
  "sky": "volcanocave"
 },
 {
  "ko": "배틀리조트",
  "region": "호연",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "타이드립호",
  "region": "호연",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "환상숲",
  "region": "호연",
  "terrain": "forest",
  "sky": "forest"
 },
 {
  "ko": "환상동굴",
  "region": "호연",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "환상산",
  "region": "호연",
  "terrain": "mountain",
  "sky": "mountain"
 },
 {
  "ko": "미개척의 숲",
  "region": "호연",
  "terrain": "forest",
  "sky": "forest"
 },
 {
  "ko": "이름없는 평원",
  "region": "호연",
  "terrain": "stonepath",
  "sky": null
 },
 {
  "ko": "미지의 동굴",
  "region": "호연",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "희미한 동굴",
  "region": "호연",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "비틀린 굴",
  "region": "호연",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "궁형의 섬",
  "region": "호연",
  "terrain": "seaside",
  "sky": "beach"
 },
 {
  "ko": "비밀의 작은 섬",
  "region": "호연",
  "terrain": "seaside",
  "sky": "beach"
 },
 {
  "ko": "창공",
  "region": "호연",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "비밀의 바위해변",
  "region": "호연",
  "terrain": "seaside",
  "sky": "beachshore"
 },
 {
  "ko": "비밀의 꽃밭",
  "region": "호연",
  "terrain": "flowers",
  "sky": "meadow"
 },
 {
  "ko": "떡잎마을",
  "region": "신오",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "축복시티",
  "region": "신오",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "무쇠시티",
  "region": "신오",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "꽃향기마을",
  "region": "신오",
  "terrain": "flowers",
  "sky": "meadow"
 },
 {
  "ko": "영원시티",
  "region": "신오",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "운하시티",
  "region": "신오",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "조아마을",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "조아의 작은 길",
  "region": "칼로스",
  "terrain": "stonepath",
  "sky": null
 },
 {
  "ko": "수미마을",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "아방쎄 도로",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "백단숲",
  "region": "칼로스",
  "terrain": "forest",
  "sky": "forest"
 },
 {
  "ko": "우베르 도로",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "백단시티",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "파르테르 가도",
  "region": "칼로스",
  "terrain": "stonepath",
  "sky": null
 },
 {
  "ko": "미르시티",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "프리즘타워",
  "region": "칼로스",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "플라드리 래버러토리",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "베르성 도로",
  "region": "칼로스",
  "terrain": "stonepath",
  "sky": null
 },
 {
  "ko": "고목내마을",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "침울한 성",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "팔레 가로수 길",
  "region": "칼로스",
  "terrain": "stonepath",
  "sky": null
 },
 {
  "ko": "파르팽 궁전",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "리비에르 라인",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "삼채시티",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "미라유 해안",
  "region": "칼로스",
  "terrain": "seaside",
  "sky": "beachshore"
 },
 {
  "ko": "가라마을",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "뿔 산길",
  "region": "칼로스",
  "terrain": "mountain",
  "sky": "mountain"
 },
 {
  "ko": "배틀샤토",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "멘히르로드",
  "region": "칼로스",
  "terrain": "stonepath",
  "sky": null
 },
 {
  "ko": "옥유마을",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "미르와르 도로",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "비춤의 동굴",
  "region": "칼로스",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "사라시티",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "마스터타워",
  "region": "칼로스",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "프라주 도로",
  "region": "칼로스",
  "terrain": "stonepath",
  "sky": null
 },
 {
  "ko": "비익시티",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "미르 황야",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "후늬 임도",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "후늬시티",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "볼 공장",
  "region": "칼로스",
  "terrain": "field",
  "sky": "thunderplains"
 },
 {
  "ko": "브렁 도로",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "버들비마을",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "트리스트 도로",
  "region": "칼로스",
  "terrain": "stonepath",
  "sky": null
 },
 {
  "ko": "프로스트케이브",
  "region": "칼로스",
  "terrain": "cave",
  "sky": "icecave"
 },
 {
  "ko": "맘모꾸리로드",
  "region": "칼로스",
  "terrain": "stonepath",
  "sky": null
 },
 {
  "ko": "향전시티",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "에뜨르와 발레 도로",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "배롱마을",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "라주 발레 도로",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "이설시티",
  "region": "칼로스",
  "terrain": "cave",
  "sky": "icecave"
 },
 {
  "ko": "미혹의 숲",
  "region": "칼로스",
  "terrain": "forest",
  "sky": "forest"
 },
 {
  "ko": "포켓몬마을",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "데르니에 도로",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "데뚜르네 도로",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "챔피언로드",
  "region": "칼로스",
  "terrain": "stonepath",
  "sky": null
 },
 {
  "ko": "포켓몬리그",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "기남시티",
  "region": "칼로스",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "배틀하우스",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "아쥐르만",
  "region": "칼로스",
  "terrain": "seaside",
  "sky": null
 },
 {
  "ko": "반짝임의 동굴",
  "region": "칼로스",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "땅이음의 동굴",
  "region": "칼로스",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "주뱃들의 소굴",
  "region": "칼로스",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "칼로스발전소",
  "region": "칼로스",
  "terrain": "field",
  "sky": "thunderplains"
 },
 {
  "ko": "플레어단 비밀기지",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "끝의 동굴",
  "region": "칼로스",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "황폐해진 호텔",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "공허의 방",
  "region": "칼로스",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "해신의 굴",
  "region": "칼로스",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "프렌드사파리",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "화염의 방",
  "region": "칼로스",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "수문의 방",
  "region": "칼로스",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "무쇠의 방",
  "region": "칼로스",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "용문양의 방",
  "region": "칼로스",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "빛의 방",
  "region": "칼로스",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "미르 스테이션",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "기남 스테이션",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "가라 수족관",
  "region": "칼로스",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "1번도로",
  "region": "알로라",
  "terrain": "stonepath",
  "sky": null
 },
 {
  "ko": "칼라에만",
  "region": "알로라",
  "terrain": "seaside",
  "sky": null
 },
 {
  "ko": "멜레멜레해",
  "region": "알로라",
  "terrain": "seaside",
  "sky": "beach"
 },
 {
  "ko": "하우올리시티",
  "region": "알로라",
  "terrain": "seaside",
  "sky": "beachshore"
 },
 {
  "ko": "릴리마을",
  "region": "알로라",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "마할로 산길",
  "region": "알로라",
  "terrain": "mountain",
  "sky": "mountain"
 },
 {
  "ko": "전쟁의 유적",
  "region": "알로라",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "텐캐럿힐",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "하우올리 묘원",
  "region": "알로라",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "멜레멜레 화원",
  "region": "알로라",
  "terrain": "flowers",
  "sky": "meadow"
 },
 {
  "ko": "바다연결동굴",
  "region": "알로라",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "나무열매 밭",
  "region": "알로라",
  "terrain": "forest",
  "sky": "forest"
 },
 {
  "ko": "우거진 동굴",
  "region": "알로라",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "하노하노리조트",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "하노하노비치",
  "region": "알로라",
  "terrain": "seaside",
  "sky": "beachshore"
 },
 {
  "ko": "아칼라 화원",
  "region": "알로라",
  "terrain": "flowers",
  "sky": "meadow"
 },
 {
  "ko": "오하나마을",
  "region": "알로라",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "환대시티",
  "region": "알로라",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "코니코니시티",
  "region": "알로라",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "로열 애버뉴",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "메모리얼힐",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "오하나목장",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "벨라화산공원",
  "region": "알로라",
  "terrain": "mountain",
  "sky": "volcanocave"
 },
 {
  "ko": "잔잔한물가언덕",
  "region": "알로라",
  "terrain": "seaside",
  "sky": "beachshore"
 },
 {
  "ko": "셰이드정글",
  "region": "알로라",
  "terrain": "forest",
  "sky": "forest"
 },
 {
  "ko": "생명의 유적",
  "region": "알로라",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "아칼라외곽",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "디그다터널",
  "region": "알로라",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "로열돔",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "울라울라 뒤쪽 해안",
  "region": "알로라",
  "terrain": "seaside",
  "sky": "beachshore"
 },
 {
  "ko": "카푸마을",
  "region": "알로라",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "하이나사막",
  "region": "알로라",
  "terrain": "desert",
  "sky": "desert"
 },
 {
  "ko": "울라울라 화원",
  "region": "알로라",
  "terrain": "flowers",
  "sky": "meadow"
 },
 {
  "ko": "포마을",
  "region": "알로라",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "말리에시티",
  "region": "알로라",
  "terrain": "town",
  "sky": "city"
 },
 {
  "ko": "말리에 정원",
  "region": "알로라",
  "terrain": "flowers",
  "sky": "meadow"
 },
 {
  "ko": "호쿠라니큰산",
  "region": "알로라",
  "terrain": "mountain",
  "sky": "mountain"
 },
 {
  "ko": "화끈산",
  "region": "알로라",
  "terrain": "mountain",
  "sky": "mountain"
 },
 {
  "ko": "결실의 유적",
  "region": "알로라",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "일륜의 호수",
  "region": "알로라",
  "terrain": "lakeside",
  "sky": "river"
 },
 {
  "ko": "월륜의 호수",
  "region": "알로라",
  "terrain": "lakeside",
  "sky": "river"
 },
 {
  "ko": "라나키라마운틴",
  "region": "알로라",
  "terrain": "mountain",
  "sky": "mountain"
 },
 {
  "ko": "수상한 저택",
  "region": "알로라",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "슈퍼・메가싸네",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "호쿠라니천문대",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "포켓몬리그",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "포니 화원",
  "region": "알로라",
  "terrain": "flowers",
  "sky": "meadow"
 },
 {
  "ko": "포니들판",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "포니옛길",
  "region": "알로라",
  "terrain": "stonepath",
  "sky": null
 },
 {
  "ko": "포니의 거친 해안",
  "region": "알로라",
  "terrain": "seaside",
  "sky": "beachshore"
 },
 {
  "ko": "포니수림",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "포니광야",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "포니해안",
  "region": "알로라",
  "terrain": "seaside",
  "sky": "beachshore"
 },
 {
  "ko": "포니험로",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "바다민족의 마을",
  "region": "알로라",
  "terrain": "seaside",
  "sky": "beach"
 },
 {
  "ko": "포니대협곡",
  "region": "알로라",
  "terrain": "mountain",
  "sky": "mountain"
 },
 {
  "ko": "일륜의 제단",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "월륜의 제단",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "피안의 유적",
  "region": "알로라",
  "terrain": "ruins",
  "sky": "earthycave"
 },
 {
  "ko": "엔드케이브",
  "region": "알로라",
  "terrain": "cave",
  "sky": "dampcave"
 },
 {
  "ko": "나시・아일랜드",
  "region": "알로라",
  "terrain": "seaside",
  "sky": "beach"
 },
 {
  "ko": "배틀트리",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "에테르파라다이스",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 },
 {
  "ko": "울트라스페이스",
  "region": "알로라",
  "terrain": "field",
  "sky": null
 }
];

/**
 * Encounters spent at one stop before moving on.
 *
 * Hunting settles every five minutes, so this is about two hours — the same
 * number server/trainer.ts uses for "one encounter in twenty-five". At 240
 * stops the whole journey runs about 21 days of
 * uptime, then starts again at 태초마을.
 */
export const LEG_LENGTH = 25;

/**
 * Where the pet is, from how much hunting has happened.
 *
 * Derived, never stored — `hunt.count` only counts up, so this needs no schema
 * bump and cannot drift. Total by construction: a missing or nonsense count
 * reads as "just set out" rather than indexing off the end.
 */
export function journeyFor(huntCount: number): Stop {
  const n = Number.isFinite(huntCount) ? Math.max(0, Math.floor(huntCount)) : 0;
  return STOPS[Math.floor(n / LEG_LENGTH) % STOPS.length];
}
